# Welcome to the Freelance Jekyll Theme
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site Configuration
title: James Bond - Freelancer Developer Designer
email: james.bond@example.com
description: James Bond is a badass secret agent that also does freelance web design and web development. Started out to pass the time between missions it grew into a life of it's own.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://awesomewebsite.com" # the base hostname & protocol for your site, e.g. http://example.com

# Information
name: James Bond

# Hero Section
hero_image: "/assets/images/hero.jpg"
hero_header: "I'm a freelance developer"

# Social Media Configuration
twitter_username: jamesbond
github_username:  jamesbond
dribbble_username: jamesbond
facebook_username: jamesbond
linkedin_username: jamesbond
instagram_username: jamesbond

# Build settings
sass:
  style: nested
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
